[package]
name = "desktop_entry"
version = "0.1.0"
authors = ["Eyal Kalderon <ebkalderon@gmail.com>"]

[dependencies]
failure = { version = "0.1.1", features = ["derive"] }
lazy_static = "1.0"
serde = { version = "1.0", features = ["derive"] }
